document.addEventListener('DOMContentLoaded', function() {
    const exportBtn = document.getElementById('exportBtn');

    if (!exportBtn) {
        console.error('Error: El botón con id="exportBtn" no fue encontrado.');
        return;
    }

    exportBtn.addEventListener('click', () => {
        chrome.cookies.getAll({ domain: "youtube.com" }, (cookies) => {
            if (chrome.runtime.lastError) {
                alert("Error al obtener cookies: " + chrome.runtime.lastError.message);
                return;
            }

            if (cookies.length === 0) {
                alert("No se encontraron cookies de YouTube.\nVisita YouTube e inicia sesión primero.");
                return;
            }

            const header = [
                "# Netscape HTTP Cookie File",
                "# Generated by Chrome YouTube Cookies Exporter",
                "# Domain: .youtube.com",
                ""
            ].join("\n");

            const cookieLines = cookies.map(cookie => {
                return [
                    ".youtube.com", // Dominio (siempre .youtube.com)
                    "TRUE",         // Incluir subdominios (TRUE)
                    cookie.path,    // Ruta de la cookie
                    "FALSE",        // Solo HTTPS (FALSE para YouTube)
                    cookie.expirationDate ? Math.round(cookie.expirationDate) : 0, // Fecha de expiración
                    cookie.name,    // Nombre de la cookie
                    cookie.value    // Valor de la cookie
                ].join("\t");       // Separar campos con tabulaciones
            });

            const content = header + "\n" + cookieLines.join("\n");
            const blob = new Blob([content], { type: "text/plain" });
            const url = URL.createObjectURL(blob);

            chrome.downloads.download({
                url: url,
                filename: "cookies.txt",
                conflictAction: "overwrite",
                saveAs: false
            }, () => {
                URL.revokeObjectURL(url);
                if (chrome.runtime.lastError) {
                    alert("Error al descargar el archivo: " + chrome.runtime.lastError.message);
                } else {
                    console.log("Cookies exportadas correctamente a cookies.txt");
                }
            });
        });
    });
});
